version: '3'
services:
  db:
   image: postgres
   networks:
    - drupal-net
   volumes:
    - postgres:/var/lib/postgresql/data
   restart: always
   env_file: .env
  #  environment: 
  #   - POSTGRES_PASSWORD=secret
  #   - POSTGRES_USER=user
  #   - POSTGRES_DB=drupal
    

  adminer:
   image: adminer
   ports:
    - 8080:8080
   networks:
    - drupal-net
   depends_on: 
    - db
  
  drupal:
   image: drupal
   ports:
    - 80:80
   networks:
    - drupal-net
   volumes:
    - dr_modules:/var/www/html/modules
    - dr_profiles:/var/www/html/dr_profiles
    - dr_themes:/var/www/html/themes
    - ./sites:/var/www/html/sites
   depends_on: 
    - adminer

networks:
  drupal-net:
volumes:
  postgres:
  dr_modules:
  dr_profiles:
  dr_themes:

    
  

  
