apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginxinc/nginx-unprivileged
        name: nginx
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
        - name: conf
          mountPath: /etc/nginx/conf.d
      - name: adapter
        image: nginx/nginx-prometheus-exporter:0.10.0
        args: ["-nginx.scrape-uri", "http://localhost:8080/basic_status"]
        ports:
          - name: http
            containerPort: 9113
            protocol: TCP
      volumes:
      - name: www
        hostPath:
          path: /tmp/www
          type: DirectoryOrCreate
      - name: conf
        hostPath:
          path: /tmp/conf
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: management
    port: 9113
    protocol: TCP
    targetPort: 9113
  type: NodePort
  selector:
    app: nginx
status:
  loadBalancer: {}
