apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: adminer
  name: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: adminer
    spec:
      containers:
      - image: adminer
        name: adminer
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: adminer
    tier: frontedn
    env: dev
  name: wp-adminer
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: adminer
  type: NodePort
status:
  loadBalancer: {}

