apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-09-30T12:09:26Z"
  generation: 1
  labels:
    app: mariadb
  name: mariadb
  namespace: default
  resourceVersion: "105278"
  selfLink: /apis/apps/v1/namespaces/default/deployments/mariadb
  uid: 122ce0ce-6602-4ec8-a2fb-bca059237563
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mariadb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mariadb
    spec:
      containers:
      - env:
        - name: MARIADB_ROOT_PASSWORD
          value: top.secret
        - name: MARIADB_DATABASE
          value: wordpress
        - name: MARIADB_USER
          value: wpuser
        - name: MARIADB_PASSWORD
          value: end321
        image: mariadb
        imagePullPolicy: Always
        name: mariadb
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2021-09-30T12:09:26Z"
    lastUpdateTime: "2021-09-30T12:09:26Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2021-09-30T12:09:26Z"
    lastUpdateTime: "2021-09-30T12:09:31Z"
    message: ReplicaSet "mariadb-576b8575d4" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 3
  updatedReplicas: 3
---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mariadb
    tier: backend
    env: prod
    customer: tuke
  name: wp-db
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mariadb
  type: NodePort
status:
  loadBalancer: {}
