apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-500
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/git/docker_images/kubernetes/data"
    type: DirectoryOrCreate
